# Generated by Django 4.1.1 on 2022-09-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("msaref", "0003_paid_done_paid_paid_up_paid_residual"),
    ]

    operations = [
        migrations.AddField(
            model_name="total",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="msaref.section",
            ),
        ),
    ]
