# Generated by Django 4.1.1 on 2022-09-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msaref", "0004_total_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="total",
            name="overall_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="total",
            name="residual_total",
            field=models.IntegerField(default=0),
        ),
    ]
