# Generated by Django 4.1.1 on 2022-09-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("msaref", "0006_band_paid_band"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paid",
            old_name="band",
            new_name="band_elm",
        ),
        migrations.AddField(
            model_name="band",
            name="paid_elm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="msaref.paid",
            ),
        ),
    ]
