# Generated by Django 4.1.1 on 2022-09-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msaref", "0008_paid_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paid",
            name="by",
        ),
    ]
