# Generated by Django 4.1.1 on 2022-10-28 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("msaref", "0009_remove_paid_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paid",
            name="band_elm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="band_elm",
                to="msaref.band",
            ),
        ),
    ]
